In [1]:
import pandas as pd
import numpy as np
labels = ['a','b','c']
list1 = [10,20,30]
a = np.array([10,20,30])
d= {'a':10,'b':20,'c':30}
pd.Series(data = list1)

0    10
1    20
2    30
dtype: int64

In [2]:
pd.Series(data = list1,index = labels)

a    10
b    20
c    30
dtype: int64

In [3]:
pd.Series(list1,labels)

a    10
b    20
c    30
dtype: int64

In [4]:
pd.Series(a)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(a,labels)

a    10
b    20
c    30
dtype: int64

In [7]:
ser1 = pd.Series([10,20,30,40], index =
['apple','mango','grapes','cherry'])
ser2 = pd.Series([10,30,40,50], index =
['apple','grapes','cherry','kiwi'])
ser1 +ser2

apple     20.0
cherry    80.0
grapes    60.0
kiwi       NaN
mango      NaN
dtype: float64

In [8]:
ser1["mango"]

np.int64(20)

In [10]:
from numpy.random import randn
np.random.seed(101)
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [11]:
df['Z']

A    0.503826
B    0.605965
C   -0.589001
D    0.955057
E    0.683509
Name: Z, dtype: float64

In [12]:
df[['Z','X']]

          Z         X
A  0.503826  0.628133
B  0.605965 -0.319318
C -0.589001  0.740122
D  0.955057 -0.758872
E  0.683509  1.978757

In [13]:
df['new'] = df['Z'] + df['W']
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [14]:
df.drop(columns ='new',axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [15]:
df.drop(columns ='new')

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [16]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [17]:
df.drop(columns ='new',axis = 1,inplace=True)
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [18]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [19]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [21]:
df.loc['A','Y']

np.float64(0.9079694464765431)

In [22]:
df.loc[['A','B'],['X','Y']]

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077

In [23]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [25]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [26]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [27]:
df['W']>0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [28]:
df[df['W']>0] ['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [29]:
df[df['W']>0][['X','Y']]

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

In [30]:
df[(df['W']>0) & (df['Y']>1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [31]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[44,55,66,44],'col3':
['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1    44  abc
1     2    55  def
2     3    66  ghi
3     4    44  xyz

In [32]:
df['col2'].unique()

array([44, 55, 66])

In [33]:
df['col3'].nunique()

4

In [34]:
df['col3'].value_counts()

col3
abc    1
def    1
ghi    1
xyz    1
Name: count, dtype: int64

In [35]:
newdf= df[(df['col1']>2) & (df['col2']==44)]
newdf

   col1  col2 col3
3     4    44  xyz

In [43]:
def times2(x):
    return x*2
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [44]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [45]:
df['col1'].sum()

np.int64(10)

In [46]:
del df['col1']
df

   col2 col3
0    44  abc
1    55  def
2    66  ghi
3    44  xyz

In [47]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [48]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [49]:
df.sort_values(by='col2') #inplace = false by default

   col2 col3
0    44  abc
3    44  xyz
1    55  def
2    66  ghi

In [50]:
df.sort_values(by='col2', inplace = True)
df

   col2 col3
0    44  abc
3    44  xyz
1    55  def
2    66  ghi

In [51]:
df.isnull()

    col2   col3
0  False  False
3  False  False
1  False  False
2  False  False